In [2]:
import numpy as np
import pandas as pd
import re

# 기획재정부

In [59]:
df = pd.read_excel('/home/eunhyea/EARTH/ConceptMap/dicdata/기획재정부.xlsx',engine='openpyxl')
print(df['설명'][4])

kw_pre = []
ex_pre = []
for kw, ex in zip(df['용어'], df['설명']):
    kw_pre.append(re.sub('\n*|\r*|\t*','',kw))
    ex_pre.append(re.sub('\n*|\r*|\t*','',ex))

df['용어_pre'] = kw_pre
df['설명_pre'] = ex_pre

df['설명_pre'][4]
df['용어_pre'][671]

2차 시장은 처음 발행된 증권, 채권 등이 거래되는 발행시장과 구분되며, 이미 발행된 주식들의 거래가 이루어지는 유통시장을 뜻한다. 국내에서는 유가증권시장, 코스닥, 코넥스, 프리보드 시장 등이 2차시장에 해당하며, 외국의 경우 New York Stock Exachange(NYSE), NASDAQ 등이 있다. 2차 시장에서는 주식이 가장 보편적으로 거래 되며, 주식 외에도 뮤추얼 펀드, 채권과 같은 상품 등도 거래된다. 패니매(Fanni Mae), 프레디맥(Freddie Mac)과 같은 기관들은 2차 시장에서 모기지 관련 상품을 거래하며 모기지 증권을 만든다.

1차 시장(Primary Market)에서는 처음 발행된 주식이나 채권을 등의 거래가 이루어지며, 흔히 알려진 거래 형태는 IPO(Initial Public Offering)이다. 이 때 거래된 증권을 후에 재판매하기 위한 거래 시장이 2차 시장이다. 각각의 거래에서 발생한 수익은 거래 당사자에게 돌아가며, 1차 시장에서 IPO 에 참여한 투자은행, 주식 발행 주체가 되는 회사 등은 2차 시장에서의 거래에 관여하지 않는다.

/home/eunhyea/miniconda3/envs/earth/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

'금융 패닉(financial panic)'

In [60]:
print(df.columns)
df.drop(columns=['용어','설명'],inplace=True)

df.rename(columns={'설명_pre':'설명', '용어_pre':'용어'}, inplace=True)

Index(['순번', '주제', '용어', '설명', '용어_pre', '설명_pre'], dtype='object')

In [61]:
df = df[['용어','설명']]

In [62]:
df.to_csv('기획재정부_pre.csv', index=False)

# 한국은행

In [63]:
df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국은행.csv')
df.drop(columns='wordCnt', inplace=True)
df.rename(columns={'ecWordNm':'용어', 'ecWordCn':'설명'}, inplace=True)

kw_pre = []
ex_pre = []
for kw, ex in zip(df['용어'], df['설명']):
    kw_pre.append(re.sub('\n*|\r*|\t*','',kw))
    ex_pre.append(re.sub('\n*|\r*|\t*','',ex))

df['용어_pre'] = kw_pre
df['설명_pre'] = ex_pre

print(df.columns)

Index(['용어', '설명', '용어_pre', '설명_pre'], dtype='object')

In [64]:
df.drop(columns=['용어','설명'],inplace=True)
df.rename(columns={'설명_pre':'설명', '용어_pre':'용어'}, inplace=True)

# df['설명'][0]
df.to_csv('한국은행_pre.csv', index=False)

# 한국투자(kor_true)

In [253]:
df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국투자.csv')
df.drop(columns='Unnamed: 0', inplace=True)
df.rename(columns={'word':'용어', 'content':'설명'}, inplace=True)

df.dropna(inplace=True)

In [254]:
import pandas as pd
import re
import ast

meta_keys = ['한자', '영문', '동의어', '참조어', '외래어']

def split_meta_and_description(text):
    if pd.isna(text):
        return [], ''

    lines = text.splitlines()
    details = []
    description_lines = []

    for line in lines:
        line = line.strip()
        matched = False
        for key in meta_keys:
            if line.startswith(f"{key} :"):
                value = line.split(":", 1)[1].strip()
                value = [v.strip() for v in value.split(',')]
                details.append({key:value})
                matched = True
                break
        if not matched:
            description_lines.append(line)

    cleaned_description = ' '.join(description_lines)
    return details, cleaned_description


# 적용
details_list = []
cleaned_descriptions = []

for text in df['설명']:
    details, cleaned = split_meta_and_description(text)
    details_list.append(details)
    cleaned_descriptions.append(cleaned)

df['details'] = details_list
df['설명'] = cleaned_descriptions

# 확인
df.head()

,용어,설명,details
0,중기대출 의무비율제도,금융기관의 대출증가액 중 일정 비율 이상을 중소기업에 지원하도록 규정한 제도이다.중...,"[{'한자': ['中企貸出 義務比率制度']}, {'동의어': ['중소기업대출 의무비..."
1,고용세,부족한 실업대책 재원을 마련하기 위해 모든 근로자 봉급에서 일정률의세금을 거두는 방...,[{'한자': ['雇傭稅']}]
2,Flagship Marketing,플래그쉽 마케팅이란 시장에서 성공을 거둔 특정상품 브랜드를 중심으로마케팅 활동을 집...,"[{'영문': ['Flagship Marketing']}, {'동의어': ['플래그..."
3,상표 전체가치,"상표 순수가치와 상표 기업가치를 합한 것으로, 상표 자체와 기업 효과부분이 결합된 ...",[]
4,상표 순수가치,상표 전체가치에서 기업효과 부분을 뺀 가치를 순수가치라고 한다.외국에서는 기업명과 ...,[]

In [255]:
def extract_kwdetails(row):

    # relation 값
    relations = []
    if row['details']:
        try:
            parsed = row['details'] # list 자료형
            if isinstance(parsed, list) and parsed:
                for el in parsed:
                    if not isinstance(el, dict):
                        continue
                    for key, value in el.items():
                        if key != '참조어':  # '참조어' 제외
                            relations.extend(value)
        except Exception as e:
            print(f"변환 오류: {e}, 값: {row['details']}")
        
        return set(relations)
    else : return None


# 새로운 컬럼 생성
df['KWdetails'] = df.apply(extract_kwdetails, axis=1)

# 확인
df.iloc[17][['KWdetails','details']]

df.drop(columns='details', inplace=True)

df.rename(columns={'KWdetails':'details'}, inplace=True)

In [256]:
df.to_csv('한국투자_pre_details.csv', index=False)

In [257]:
df[['용어','설명']].to_csv('한국투자_pre.csv', index=False)

# 한국경제

In [90]:
import pandas as pd
import re

df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국경제.csv', header=0)

df.rename(columns={'0':'용어', '1':'details', '2':'설명'}, inplace=True)

# details 컬럼 가공
details_cleaned = []

for row in df['details']:
    if isinstance(row, str):  # 문자열인 경우에만 split 수행
        # 쉼표로 나누고 양쪽 공백 제거
        split_row = [item.strip() for item in row.split(',') if item.strip()]
        details_cleaned.append(split_row)
    else:
        # NaN 등 비문자열인 경우 빈 리스트 추가
        details_cleaned.append(None)

# 새 컬럼으로 추가
df['details_list'] = details_cleaned

df.drop(columns='details', inplace=True)
df.rename(columns={'details_list':'details'}, inplace=True)

df

,용어,설명,details
0,가격분석,"기업이 제품 또는 서비스의 가격을 결정하기 위해 수행하는 일련의 과정. 원가, 시장...",[price analysis]
1,가격선도,"과점 시장에서 특정 기업이 시장 가격을 주도적으로 결정하고, 다른 기업들이 이를 따...",[price leadership]
2,가격지정 주문,투자자가 시세가 매매위탁 당시의 시세보다 상승하여 자기의 지정가격을 넘어설 때는 지...,[stop order]
3,가격연동제,가격 연동제는 특정 상품의 가격을 다른 상품의 가격과 연관 지어 결정하는 시장 가격...,"[價格連動制, price sliding system]"
4,가격우선의 원칙,증권시장의 경쟁매매에 있어 호가의 우선순위를 정하는 것으로서 파는 경우는 낮은 가격...,[priority of best quotation principle]
...,...,...,...
13579,국제전기통신연합,국제전기통신연합(International Telecommunication Union...,"[International Telecommunication Union, ITU]"
13580,라이트스피드,'라이트스피드(Lightspeed)'는 캐나다 텔레샛(Telesat)이 추진 중인 ...,[Lightspeed]
13581,텔레샛,"텔레샛(Telesat) 은 캐나다 오타와에 본사를 둔 세계적인 위성통신 기업으로, ...",[Telesat]
13582,카이퍼 프로젝트,"카이퍼 프로젝트는 아마존(Amazon)이 개발 중인 저궤도 위성 인터넷 네트워크로,...",[Project Kuiper]
13583,궈왕,궈왕은 중국 정부가 추진하는 국가 주도형 저궤도(LEO) 위성 기반 글로벌 인터넷 ...,"[國網, Guowang]"

In [91]:
df = df[['용어', '설명']]
df[df.isna().any(axis=1)]

            용어   설명
271   구매조건부 리스  NaN
400      기가바이트  NaN
402        기계어  NaN
403     기계투자효율  NaN
1966      중앙은행  NaN

In [72]:
kw_pre = []
ex_pre = []
for kw, ex in zip(df['용어'], df['설명']):
    # NaN 처리: 문자열이 아닌 경우 빈 문자열로 대체
    kw = '' if pd.isna(kw) else kw
    ex = '' if pd.isna(ex) else ex
    
    kw_pre.append(re.sub('\n*|\r*|\t*','',kw))
    ex_pre.append(re.sub('\n*|\r*|\t*','',ex))

df['용어_pre'] = kw_pre
df['설명_pre'] = ex_pre

print(df.columns)

Index(['용어', '설명', '용어_pre', '설명_pre'], dtype='object')

In [73]:
df.drop(columns=['용어','설명'],inplace=True)
df.rename(columns={'설명_pre':'설명', '용어_pre':'용어'}, inplace=True)

# df['설명'][0]
df.to_csv('한국경제_pre.csv', index=False)

# 재정경제통계시스템

In [1]:
import pandas as pd
import re

df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/재정경제통계시스템.csv', header=0)
df.drop(columns='순번', inplace=True)
df[df.isna().any(axis=1)]
# df.rename(columns={'0':'용어', '1':'details', '2':'설명'}, inplace=True)

Empty DataFrame
Columns: [용어, 설명]
Index: []

In [2]:
kw_pre = []
ex_pre = []
for kw, ex in zip(df['용어'], df['설명']):
    # NaN 처리: 문자열이 아닌 경우 빈 문자열로 대체
    kw = '' if pd.isna(kw) else kw
    ex = '' if pd.isna(ex) else ex
    
    kw_pre.append(re.sub('\n*|\r*|\t*','',kw))
    ex_pre.append(re.sub('\n*|\r*|\t*','',ex))

df['용어_pre'] = kw_pre
df['설명_pre'] = ex_pre

print(df.columns)

Index(['용어', '설명', '용어_pre', '설명_pre'], dtype='object')

In [3]:
df.drop(columns=['용어','설명'],inplace=True)
df.rename(columns={'설명_pre':'설명', '용어_pre':'용어'}, inplace=True)

# df['설명'][0]
df.to_csv('재정경제통계시스템_pre.csv', index=False)

# 조달청

In [77]:
import pandas as pd
import re

df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/조달청.csv', header=0)
# df.drop(columns='순번', inplace=True)
df.rename(columns={'name':'용어', 'content':'설명'}, inplace=True)
df

          용어                                                 설명
0     가중주가평균  단순주가평균이나 수정주가평균은 채용종목의 주가만을 산술평균한데\r\n 비하여 가중주...
1     가중평균금리  금융기관에서 취급하는 금융상품의 금리를 사용빈도나 금액의 비중으로 가중치를 두어 평...
2    가치 베이시스  선물의 이론가격과 실제가격 간의 차이로, 이것은 선물거래가 선물의 공정한 가치에 비...
3       간접금융  직접금융에 반대되는 개념으로 자금의 최종공급자와 최종수요자 사이에 은행 등의 금융기...
4         강세         시세가 상승하는 경향이 있거나 앞으로 상승할 것으로 예측되는 장세를 말한다.
..       ...                                                ...
488   휴면예금계좌  금융기관들은 소액의 수시입출식 예금(보통예금, 저축예금 등)계좌 중 일정기간 입출금...
489    흑자 도산  기업의 도산은 일반적으로 과중한 적자로 경영이 유지되지 못할 경우에 발생하지만 흑자...
490     흑자재정  공채, 차입금 이외의 세입이 공채 원본의 상환을 차감 한 세출을 초과하는 재정을 말...
491   희망대량매매  「사자」는 사람이 정해지지 않은 상태에서 「팔자」는 쪽에서 수량과 가격을 정해 먼저...
492      희석화  주식의 가치가 낮아지는 것을 말한다. 신주를 발행하는 경우 주식 수가 늘어나는 만큼...

[493 rows x 2 columns]

In [78]:
kw_pre = []
ex_pre = []
for kw, ex in zip(df['용어'], df['설명']):
    # NaN 처리: 문자열이 아닌 경우 빈 문자열로 대체
    kw = '' if pd.isna(kw) else kw
    ex = '' if pd.isna(ex) else ex
    
    kw_pre.append(re.sub('\n*|\r*|\t*','',kw))
    ex_pre.append(re.sub('\n*|\r*|\t*','',ex))

df['용어_pre'] = kw_pre
df['설명_pre'] = ex_pre

print(df.columns)

Index(['용어', '설명', '용어_pre', '설명_pre'], dtype='object')

In [79]:
df.drop(columns=['용어','설명'],inplace=True)
df.rename(columns={'설명_pre':'설명', '용어_pre':'용어'}, inplace=True)

# df['설명'][0]
df.to_csv('조달청_pre.csv', index=False)

# 국립국어원

In [259]:
import numpy as np
import pandas as pd

import ast


df = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/국립국어원.csv', header=0)

df.replace({np.nan: ''}, inplace=True)

def extract_kwdetails(row):
    # origin 값
    origin = row['origin'] if pd.notna(row['origin']) else ''
    
    # translations 값에서 'translation'만 추출
    translations = ''
    if row['translations']:
        try:
            parsed = ast.literal_eval(row['translations'])
            if isinstance(parsed, list) and parsed:
                translations = parsed[0].get('translation', '').strip()
        except Exception as e:
            print(f"변환 오류: {e}, 값: {row['translations']}")

    # relation 값
    relations = []
    if row['related']:
        try:
            parsed = ast.literal_eval(row['related'])
            if isinstance(parsed, list) and parsed:
                for el in parsed:
                    if el.get('category', '') != '참고어':
                        val = el.get('values', '')
                        # 'values'가 set일 경우, 리스트로 풀어주기
                        if isinstance(val, set):
                            relations.extend(list(val))  # set -> list
                        elif isinstance(val, list):
                            relations.extend(val)       # 이미 리스트면 그대로
                        elif isinstance(val, str):
                            relations.append(val)       # 단일 문자열
        except Exception as e:
            print(f"변환 오류: {e}, 값: {row['related']}")

    result = []
    if origin:
        result.append(origin.strip())
    if translations:
        result.append(translations)
    if relations:
        result.extend(relations)
    
    # return ', '.join(set(result))
    return set(result)


# 새로운 컬럼 생성
df['KWdetails'] = df.apply(extract_kwdetails, axis=1)
df_pre = df[['korean', 'definition', 'KWdetails']].rename(columns={'korean':'용어', 'definition':'설명', 'KWdetails':'details'})
df_pre.to_csv('국립국어원_pre_details.csv',index=False)

df_pre = df[['korean', 'definition']].rename(columns={'korean':'용어', 'definition':'설명', 'KWdetails':'details'})
df_pre.to_csv('국립국어원_pre.csv', index=False)

# 하나로 합치기

In [38]:
import pandas as pd 

df1 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/기획재정부_pre.csv', header=0)
df2 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국은행_pre.csv', header=0)
df3 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국투자_pre_details.csv', header=0)
df4 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/한국경제_pre.csv', header=0)
df5 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/재정경제통계시스템_pre.csv', header=0)
df6 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/조달청_pre.csv', header=0)
df7 = pd.read_csv('/home/eunhyea/EARTH/ConceptMap/dicdata/국립국어원_pre_details.csv', header=0)

df_final = pd.concat([df1, df2, df3, df4, df5, df6, df7], axis=0)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69980 entries, 0 to 34924
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   용어       69980 non-null  object
 1   설명       69904 non-null  object
 2   details  49008 non-null  object
dtypes: object(3)
memory usage: 2.1+ MB

In [39]:
# 결측값 확인
print(len(df_final[df_final[['용어','설명']].isna().any(axis=1)]))

# 결측값 제거
df_final.dropna(inplace=True, subset=['용어','설명'])
df_final.info()

76
<class 'pandas.core.frame.DataFrame'>
Index: 69904 entries, 0 to 34924
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   용어       69904 non-null  object
 1   설명       69904 non-null  object
 2   details  48937 non-null  object
dtypes: object(3)
memory usage: 2.1+ MB

In [40]:
# 설명이 더 긴 용어(ascending=False) 순서대로 정렬
df_final_sorted = df_final \
                        .sort_values(by='설명', key=lambda x: x.str.len(), ascending=False)
# 이상한 설명 제거
df_final_sorted = df_final_sorted[:-5]

df_final_sorted.to_csv('통합_ver1.csv', index=False)

# 중복값 처리

In [117]:
import re

df_sorted = pd.read_csv('통합_ver1.csv', header=0)
# df_sorted.fillna('',inplace=True) # 모든 컬럼 문자열로 전처리함....

# 1) details 컬럼(문자열로 된 "['A','B',...]" 형태)을 실제 리스트로
def to_set(x):
    if isinstance(x, str):
        try:
            lst = ast.literal_eval(x)
            return set(lst) if isinstance(lst, (set, tuple)) else set()
        except:
            # "A, B, C" 처럼 리스트 리터럴이 아닐 때
            return [p.strip() for p in x.split(',') if p.strip()]
    elif isinstance(x, (set, tuple)):
        return set(x)
    else:
        return set()

df_sorted['details_list'] = df_sorted['details'].apply(to_set)
df_sorted

,용어,설명,details,details_list
0,중대재해처벌법,중대재해가 발생하는 경우 안전조치를 소홀히 한 사업주나 경영책임자에게 1년 이상의 ...,NaN,{}
1,MSCI 선진국지수,미국의 금융지수 정보제공 회사인 모건스탠리 캐피털 인터내셔널 (Morgan Stan...,NaN,{}
2,디폴트 옵션,확정기여(DC)형 퇴직연금에 가입한 근로자가 특별한 운용 지시를 하지 않을 경우 사...,NaN,{}
3,2023 세법개정안,기획재정부가 2023년 7월 27일 서울 명동 은행회관에서 세제발전심의위원회를 열고...,NaN,{}
4,대체 불가능 토큰,블록체인 상에서 유통되는 토큰의 한 종류로 각 토큰마다 고유 값을 가지고 있어 다른...,NaN,{}
...,...,...,...,...
69894,저이자,낮은 이자.,{'低利子'},{低利子}
69895,화차,화물 자동차,NaN,{}
69896,쇼트 클립,짧은 동영상,NaN,{}
69897,해운,해상 운송,NaN,{}
69898,임목,숲의 나무,NaN,{}

In [118]:
# 2) 괄호 안 텍스트를 set에 add
def add_parenthesis(details: set, term: str) -> set:
    # details: 기존 set
    # term: '용어' 문자열, 예: '인공지능(AI: Artificial Intelligence)'
    m = re.search(r'\((?=\D)([^)]*)\)', term)
    if m:
        extra = m.group(1).strip()
        if extra:
            # 방법 1: in-place로 추가
            details.add(extra)
    return details

df_sorted['details_list'] = df_sorted.apply(
    lambda row: add_parenthesis(row['details_list'], row['용어']),
    axis=1
)
df_sorted

,용어,설명,details,details_list
0,중대재해처벌법,중대재해가 발생하는 경우 안전조치를 소홀히 한 사업주나 경영책임자에게 1년 이상의 ...,NaN,{}
1,MSCI 선진국지수,미국의 금융지수 정보제공 회사인 모건스탠리 캐피털 인터내셔널 (Morgan Stan...,NaN,{}
2,디폴트 옵션,확정기여(DC)형 퇴직연금에 가입한 근로자가 특별한 운용 지시를 하지 않을 경우 사...,NaN,{}
3,2023 세법개정안,기획재정부가 2023년 7월 27일 서울 명동 은행회관에서 세제발전심의위원회를 열고...,NaN,{}
4,대체 불가능 토큰,블록체인 상에서 유통되는 토큰의 한 종류로 각 토큰마다 고유 값을 가지고 있어 다른...,NaN,{}
...,...,...,...,...
69894,저이자,낮은 이자.,{'低利子'},{低利子}
69895,화차,화물 자동차,NaN,{}
69896,쇼트 클립,짧은 동영상,NaN,{}
69897,해운,해상 운송,NaN,{}
69898,임목,숲의 나무,NaN,{}

In [122]:
# 3) 용어에서 괄호 제거
df_sorted['term_clean'] = df_sorted['용어'].str.replace(r'\([^)]*\)', '', regex=True).str.strip()

# 4) 최종 details_pre 리스트로 합치기 (term_clean + details_list)
df_sorted['details_pre_list'] = df_sorted.apply(
    lambda r: set(r['details_list']) | {r['term_clean']},
    axis=1
)

# 5) 띄어쓰기 제거 동의어도 추가
df_sorted['details_pre_list'] = df_sorted.apply(
    lambda r: set(r['details_pre_list']) 
              | { re.sub(r'\s+', '', r['term_clean']) } 
              if r['term_clean'] else set(r['details_pre_list']),
    axis=1
)

df_sorted

,용어,설명,details,details_list,term_clean,details_pre_list
0,중대재해처벌법,중대재해가 발생하는 경우 안전조치를 소홀히 한 사업주나 경영책임자에게 1년 이상의 ...,NaN,{},중대재해처벌법,{중대재해처벌법}
1,MSCI 선진국지수,미국의 금융지수 정보제공 회사인 모건스탠리 캐피털 인터내셔널 (Morgan Stan...,NaN,{},MSCI 선진국지수,"{MSCI선진국지수, MSCI 선진국지수}"
2,디폴트 옵션,확정기여(DC)형 퇴직연금에 가입한 근로자가 특별한 운용 지시를 하지 않을 경우 사...,NaN,{},디폴트 옵션,"{디폴트 옵션, 디폴트옵션}"
3,2023 세법개정안,기획재정부가 2023년 7월 27일 서울 명동 은행회관에서 세제발전심의위원회를 열고...,NaN,{},2023 세법개정안,"{2023세법개정안, 2023 세법개정안}"
4,대체 불가능 토큰,블록체인 상에서 유통되는 토큰의 한 종류로 각 토큰마다 고유 값을 가지고 있어 다른...,NaN,{},대체 불가능 토큰,"{대체불가능토큰, 대체 불가능 토큰}"
...,...,...,...,...,...,...
69894,저이자,낮은 이자.,{'低利子'},{低利子},저이자,"{低利子, 저이자}"
69895,화차,화물 자동차,NaN,{},화차,{화차}
69896,쇼트 클립,짧은 동영상,NaN,{},쇼트 클립,"{쇼트 클립, 쇼트클립}"
69897,해운,해상 운송,NaN,{},해운,{해운}
69898,임목,숲의 나무,NaN,{},임목,{임목}

In [127]:
df_sorted['details_pre'] = df_sorted['details_pre_list'].apply(lambda lst: ', '.join(lst))
df_synoynms = df_sorted.drop(columns=['details','details_list','term_clean'])
df_synoynms.to_csv('통합_ver2.csv', index=False)

In [128]:
df_synoynms.info()
df_synoynms

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69899 entries, 0 to 69898
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   용어                69899 non-null  object
 1   설명                69899 non-null  object
 2   details_pre_list  69899 non-null  object
 3   details_pre       69899 non-null  object
dtypes: object(4)
memory usage: 2.1+ MB

,용어,설명,details_pre_list,details_pre
0,중대재해처벌법,중대재해가 발생하는 경우 안전조치를 소홀히 한 사업주나 경영책임자에게 1년 이상의 ...,{중대재해처벌법},중대재해처벌법
1,MSCI 선진국지수,미국의 금융지수 정보제공 회사인 모건스탠리 캐피털 인터내셔널 (Morgan Stan...,"{MSCI선진국지수, MSCI 선진국지수}","MSCI선진국지수, MSCI 선진국지수"
2,디폴트 옵션,확정기여(DC)형 퇴직연금에 가입한 근로자가 특별한 운용 지시를 하지 않을 경우 사...,"{디폴트 옵션, 디폴트옵션}","디폴트 옵션, 디폴트옵션"
3,2023 세법개정안,기획재정부가 2023년 7월 27일 서울 명동 은행회관에서 세제발전심의위원회를 열고...,"{2023세법개정안, 2023 세법개정안}","2023세법개정안, 2023 세법개정안"
4,대체 불가능 토큰,블록체인 상에서 유통되는 토큰의 한 종류로 각 토큰마다 고유 값을 가지고 있어 다른...,"{대체불가능토큰, 대체 불가능 토큰}","대체불가능토큰, 대체 불가능 토큰"
...,...,...,...,...
69894,저이자,낮은 이자.,"{低利子, 저이자}","低利子, 저이자"
69895,화차,화물 자동차,{화차},화차
69896,쇼트 클립,짧은 동영상,"{쇼트 클립, 쇼트클립}","쇼트 클립, 쇼트클립"
69897,해운,해상 운송,{해운},해운
69898,임목,숲의 나무,{임목},임목

In [129]:
# 중복 용어 확인 
df_synoynms[df_synoynms.duplicated('용어', keep=False)].sort_values('용어')

,용어,설명,details_pre_list,details_pre
23106,0.5인 가구,싱글족 가운데 두 곳 이상에 거처를 두거나 잦은 여행과 출장 등으로 오랫동안 집을 ...,"{0.5인 가구, 0.5인가구}","0.5인 가구, 0.5인가구"
17112,0.5인 가구,싱글족 가운데 2곳 이상에 거처를 두거나 잦은 여행과 출장으로 집을 오래 비우는 사...,"{0.5인 가구, 0.5인가구}","0.5인 가구, 0.5인가구"
19147,1월효과,뚜렷한 이유없이 1월의 주가 상승률이 다른 달에 비해 높아지는 현상. 세금을 회피하...,{1월효과},1월효과
25288,1월효과,매년 1월 초에 주식시장은 배당락 시세를 회복하며서 매우 강한 강세가나타나는 것이 ...,"{1月效果, January effect, 1월효과}","1月效果, January effect, 1월효과"
16861,1인 창조기업,"개인이 사장이면서 직원인 기업을 의미한다. 자신이 가진 '지식, 경험, 기술' 등을...","{1인 창조기업, 1인창조기업}","1인 창조기업, 1인창조기업"
...,...,...,...,...
47145,희소성의 법칙,사회 구성원들의 욕망은 무한한 데 비하여 그 욕망을 채워 줄 수 있는 자원이나 수단...,"{희소성의법칙, 稀少性 의 法則, law of scarcity, 희소성의 법칙, 희...","희소성의법칙, 稀少性 의 法則, law of scarcity, 희소성의 법칙, 희소..."
56013,히든 챔피언,해당 분야에서 세계 시장을 지배하고 있지만 대중에게는 잘 알려지지 않은 우량 기업.,"{hidden champion, 히든챔피언, 히든 챔피언}","hidden champion, 히든챔피언, 히든 챔피언"
13273,히든 챔피언,독일 경영학자인 헤르만 지몬이 2008년에 발간한 저서 ''히든 챔피언''에서 소개...,"{히든챔피언, 히든 챔피언}","히든챔피언, 히든 챔피언"
41790,힌덴부르크 오멘,여러 기술적 지표들을 분석하여 증시가 큰 폭으로 떨어질 조짐을 예측하는 기법. 19...,"{Hindenburg omen, 힌덴부르크오멘, 힌덴부르크 오멘}","Hindenburg omen, 힌덴부르크오멘, 힌덴부르크 오멘"
21747,힌덴부르크 오멘,증시에서 각종 지표를 바탕으로 대폭락을 예측하는 기술적 기법 중 하나다. 1년래 최...,"{힌덴부르크오멘, 힌덴부르크 오멘}","힌덴부르크오멘, 힌덴부르크 오멘"

In [130]:
df_synoynms[df_synoynms['용어']=='국내총생산']

,용어,설명,details_pre_list,details_pre
6779,국내총생산,한 나라의 경제규모를 나타내는 지표. 가계·기업·정부 등 경제 주체들이 일정기간 동...,{국내총생산},국내총생산
18389,국내총생산,"국내총생산은 한 나라의 영역내에서 가계, 기업, 정부 등 모든 경제주체가 일정기간동...","{GDP, 國內總生産, 국내총생산}","GDP, 國內總生産, 국내총생산"

In [131]:
df_synoynms[df_synoynms['용어']=='국내 총생산']

,용어,설명,details_pre_list,details_pre
27913,국내 총생산,"국민 총생산(GNP)에서 해외로부터의 순소득을 뺀 것이며, 어느 한 나라의 순전한 ...","{국내 총생산, 國內總生産, 국내총생산, Gross Domestic Product}","국내 총생산, 國內總生産, 국내총생산, Gross Domestic Product"
50505,국내 총생산,국민 총생산에서 투자 수익 따위의 해외로부터의 순소득을 제외한 지표. 경제 성장의 ...,"{지디피, 국내 총생산, 國內總生産, 국내총생산}","지디피, 국내 총생산, 國內總生産, 국내총생산"

In [132]:
df_synoynms[df_synoynms['용어']=='GDP']

,용어,설명,details_pre_list,details_pre
24075,GDP,국민 총생산에서 해외로부터의 순소득을 뺀 것이며 어느 한 나라의 순전한 국내경제활...,"{GDP, gross domestic product, 국내총생산}","GDP, gross domestic product, 국내총생산"
56595,GDP,국내에서 일정기간 내에 발생된 재화와 용역의 순가치를 생산면에서 포착한 총합계액,{GDP},GDP

In [133]:
df_synoynms[df_synoynms['용어']=='지디피']

,용어,설명,details_pre_list,details_pre
50546,지디피,국민 총생산에서 투자 수익 따위의 해외로부터의 순소득을 제외한 지표. 경제 성장의 ...,"{국내 총생산, GDP, 지디피}","국내 총생산, GDP, 지디피"

In [135]:
df_synoynms[df_synoynms['용어']=='외환율']

,용어,설명,details_pre_list,details_pre
59351,외환율,자기 나라 돈과 다른 나라 돈의 교환 비율. 외국환 시장에서 결정된다.,"{外換率, 외국환 시세, 외환율, 환율, 환시세, 외환 시세}","外換率, 외국환 시세, 외환율, 환율, 환시세, 외환 시세"

In [134]:
df_synoynms[df_synoynms['용어']=='환율']

,용어,설명,details_pre_list,details_pre
8618,환율,"일 국과 타국의 통화가치의 비율, 즉 양국통화의 교환비율을 말하며 일 국 통화의 대...",{환율},환율
12347,환율,"서로 다른 통화의 교환비율, 즉 환율을 가리키는 말이며 환시세 또는 환율이라고도 한...","{환율, 外國換時勢, 외국환 시세, rate of foreign exchange}","환율, 外國換時勢, 외국환 시세, rate of foreign exchange"
14532,환율,한 나라의 통화가 다른 통화로 교환되는 가격. 환율은 어떤 두 나라의 물건값을 서로...,{환율},환율
21480,환율,화폐간 교환비율. 두 화폐의 상대적 가치를 나타낸다. 만약 미화 1달러를 얻기 위하...,{환율},환율
37941,환율,한 통화가 다른 통화로 구매할 수 있는 한 통화 가격이 사용하는 통화간 및 순 수익...,"{환율, exchange rate}","환율, exchange rate"
59421,환율,자기 나라 돈과 다른 나라 돈의 교환 비율. 외국환 시장에서 결정된다.,"{換率, 외환율, 외국환 시세, 환율, 환시세, 외환 시세}","換率, 외환율, 외국환 시세, 환율, 환시세, 외환 시세"
66509,환율,자기 나라 통화와 다른 나라 통화의 교환비율.,"{환율, 換率}","환율, 換率"

In [ ]:
import pandas as pd
import ast
from collections import defaultdict

# --- 1. DataFrame 불러오기 (예시) ------------------------------------------
df = pd.read_csv('통합_ver2.csv', header=0)

# --- 2. 'details_pre' 컬럼에서 실제 set 형태로 꺼내기 ---------------------------
def parse_details(x):
    """
    details_pre 컬럼이
      - 리스트/셋 객체이면 그대로 set으로 변환,
      - 문자열이면 ',' 를 구분자로 분리해 set 생성,
      - 그 외(None, NaN)이면 빈 set 반환
    """
    if isinstance(x, (list, set)):
        return set(x)
    if not isinstance(x, str):
        return set()
    # 쉼표로 분리
    parts = [p.strip() for p in x.split(',')]
    # 빈 문자열 제거
    return set([p for p in parts if p]).union({p.lower() for p in parts if p})

# 적용
df['details_set'] = df['details_pre'].apply(parse_details)

# --- 3. Union–Find(Disjoint Set) 으로 동의어 그룹 만들기 ---------------------
parent = {}

def find(u):
    parent.setdefault(u, u)
    if parent[u] != u:
        parent[u] = find(parent[u])
    return parent[u]

def union(a, b):
    ra, rb = find(a), find(b)
    if ra != rb:
        parent[rb] = ra

# (A) 모든 용어(term)를 parent에 등록
for term in df['용어']:
    parent.setdefault(term, term)

# (B) detail → 용어 리스트 매핑
from collections import defaultdict
detail_to_terms = defaultdict(list)
for term, details in zip(df['용어'], df['details_set']):
    for d in details:
        detail_to_terms[d].append(term)

# (C) 같은 detail을 공유하는 용어들끼리 union
for detail, terms in detail_to_terms.items():
    # detail로 연결된 term 그룹이 2개 이상일 때만
    if len(terms) > 1:
        first = terms[0]
        for other in terms[1:]:
            union(first, other)
# ------------------------------------------------------------------------------

# --- 4. 각 용어가 속한 대표(root)를 찾아 'component' 컬럼에 기록 -------------
df['component'] = df['용어'].apply(find)
# -----------------------------------------------------------------------------


# --- 5. component별로 용어 그룹 매핑하기 -------------------------
from collections import defaultdict

# component(root) → 전체 그룹(용어 + 모든 details) 매핑
comp_to_group = defaultdict(set)
for term, details, comp in zip(df['용어'], df['details_set'], df['component']):
    # 1) 원래 용어도 추가
    comp_to_group[comp].add(term)
    # 2) 그 용어에 딸린 모든 details_set 아이템도 추가
    comp_to_group[comp].update(details)

# 각 행에 해당 component 의 전체 그룹을 set 으로 할당
df['details_group'] = df['component'].map(comp_to_group)

# --- 5. 그룹별로 대표 행만 골라내기 -------------------------
keep_idxs = []
for comp, group_df in df.groupby('component'):
    # 1) component(대표어)와 용어(term)가 같은 행이 있으면 그 행의 idx 사용
    is_canon = group_df['용어'] == comp
    if is_canon.any():
        idx = group_df[is_canon].index[0]
    else:
        # 2) 아니면 기존처럼 설명 길이 최댓값 행
        idx = group_df['설명'].str.len().idxmax()
    keep_idxs.append(idx)

# 최종 결과 DataFrame
df_dedup = df.loc[keep_idxs].drop(columns=['details_set', 'component', 'details_pre']).reset_index(drop=True)
# -------------------------------------------------------------------------

# --- 6. 결과 확인 ---------------------------------------------------------
print(f"원본 {len(df)}개 → 중복 제거 후 {len(df_dedup)}개")
df_dedup.info()

원본 69899개 → 중복 제거 후 45798개
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45798 entries, 0 to 45797
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   용어                45798 non-null  object
 1   설명                45798 non-null  object
 2   details_pre_list  45798 non-null  object
 3   details_group     45798 non-null  object
dtypes: object(4)
memory usage: 1.4+ MB

In [155]:
df_dedup

,용어,설명,details_pre_list,details_group
0,''덕후'' 문화,일본어 ‘오타쿠(オタク)’를 한국식으로 표기한 ‘오덕후’에서 온 ‘덕후’는 온라인상...,"{""''덕후''문화"", ""''덕후'' 문화""}","{''덕후''문화, ''덕후'' 문화}"
1,'지놈'과 '게놈',Genome은 `유전자'를 뜻하는 gen과 `염색체'를 뜻하는 chromosom을 ...,"{""'지놈'과 '게놈'"", ""'지놈'과'게놈'""}","{'지놈'과 '게놈', '지놈'과'게놈'}"
2,0.5인 가구,싱글족 가운데 2곳 이상에 거처를 두거나 잦은 여행과 출장으로 집을 오래 비우는 사...,"{'0.5인 가구', '0.5인가구'}","{0.5인 가구, 0.5인가구}"
3,014XY 네트워크,일반 전화보다 저렴한 통신요금체계인 데이터 통신용 고속 전화회선을말한다. 1997년...,"{'014XY 네트워크', '014XY네트워크', '014XY Network'}","{014XY 네트워크, 014xy 네트워크, 014XY네트워크, 014xy네트워크,..."
4,0810프로젝트,2008년 베이징올림픽과 2010년 상하이엑스포를 계기로 중국 정부가 추진하는 각종...,{'0810프로젝트'},{0810프로젝트}
...,...,...,...,...
45793,ＢＪR증후군,Ａ그룹은 ＩＭＦ시대 1년이 다가도록 외채가 전혀 줄지 않아 현재 약100억달러가량 ...,"{'ＢＪR症候群', 'ＢＪR증후군', '배째라증후군'}","{ｂｊr症候群, ＢＪR증후군, 배째라증후군, ＢＪR症候群, ｂｊr증후군}"
45794,ＦＴ/Ｓ&Ｐ월드인덱스 정책위원회,ＦＴＳＥ인터내셔널사가 발표하는 ＦＴ지수중 세계증시를 대상으로산출하는 ＦＴ/Ｓ&Ｐ월드...,"{'ＦＴ/Ｓ&Ｐ월드인덱스 정책위원회', 'ＦＴ/Ｓ&Ｐ월드인덱스정책위원회'}","{ＦＴ/Ｓ&Ｐ월드인덱스정책위원회, ｆｔ/ｓ&ｐ월드인덱스 정책위원회, ｆｔ/ｓ&ｐ월드..."
45795,ＯＲＭ,기업의 운영자원을 관리해주는 사업ＯＲＭ은 사무용품을 비롯해 기업이 필요로 하는 모든...,"{'Ｏperating Ｒesource Ｍanagement', 'ＯＲＭ'}","{ｏｒｍ, Ｏperating Ｒesource Ｍanagement, ＯＲＭ, ｏper..."
45796,ＳＤＴ,인터넷 공간에서 신용카드없이 계좌이체를 통해 전자상거래 할 수있는 사이버 직불카드 ...,"{'Ｓecure Ｄebit Ｔransaction', 'ＳＤＴ'}","{ｓecure ｄebit ｔransaction, ＳＤＴ, ｓｄｔ, Ｓecure Ｄe..."
45797,ＴＶ인터넷 사업,ＰＣ대신 ＴＶ를 이용해 인터넷에 접속할 수 있는 장비를 개발하고인터넷포털서비스 전자...,"{'ＴＶ인터넷사업', 'ＴＶ인터넷 사업'}","{ＴＶ인터넷사업, ｔｖ인터넷 사업, ＴＶ인터넷 사업, ｔｖ인터넷사업}"

In [162]:
# 외환율, 외국환 시세, 환율, 환시세, 외환 시세
# 1) 마스크 만들기: 각 행의 details_pre_list에 '환율'이 있으면 True
mask = df_dedup['details_group'].apply(lambda lst: '경제성장' in lst)

# 2) 해당 마스크로 DataFrame 필터링
[i for i in df_dedup[mask]['details_group']]

[{'經濟成長', '경제 성장', '경제성장'}]

In [146]:
df_dedup[df_dedup['용어']=='외국환시세']

,용어,설명,details_pre_list,details_group
29038,외국환시세,서로 다른 통화의 교환비율 즉 환율을 가리키는 말이며 환시세 또는 그냥 환율이라고도...,"{'환율', '외국환시세', '外國換時勢', 'rate of foreign exch...","{exchange rate, rate of foreign exchange, 환시세,..."

In [163]:
# '용어' 컬럼 기준으로 오름차순 정렬
df_dedup = df_dedup.sort_values(by='용어', ascending=True).reset_index(drop=True)

# 용어가 두글자 미만인 row drop
df_dedup = df_dedup[df_dedup['용어'].str.len() >= 2].reset_index(drop=True)
df_dedup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45729 entries, 0 to 45728
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   용어                45729 non-null  object
 1   설명                45729 non-null  object
 2   details_pre_list  45729 non-null  object
 3   details_group     45729 non-null  object
dtypes: object(4)
memory usage: 1.4+ MB

In [164]:
df_dedup.to_csv('통합_ver3.csv', index=False)

In [33]:
df_dedup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46483 entries, 0 to 46482
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   용어             46483 non-null  object
 1   설명             46483 non-null  object
 2   details_group  46483 non-null  object
dtypes: object(3)
memory usage: 1.1+ MB

In [ ]:
'''
국내총생산  |	한 나라의 경제규모를 나타내는 지표. 가계·기업·정부 등 경제 주체들이 일정기간 동안 생산한 재화·서비스의 가치를 시장가격으로 모두 합한 것. 최종생산물의 가치를 모두 더해서 계산할 수도 있고 각 생산단계에서 추가된 부가가치를 더해서 구할 수도 있다. 쉽게 말해 한 국가의 자동차, 신규 주택, 전자제품, 식료품 등 재화의 판매가격과 의료비와 같은 서비스 가격, 그리고 특정 기간동안 수입한 제품의 가격표를 모두 더한 것이라고 할 수 있다. 아직 팔리지 않고 창고에 재고로 쌓여있는 상품도 포함되지만 중간재 가격은 들어가지 않는다. 단순한 소득이전은 새로운 가치를 창출한 것이 아니므로 포함되지 않는다. '시장가치'란 GDP는 시장에서 거래되는 가격으로 평가하므로 원칙적으로 시장에서 거래되는 것만 포함한다.	
국내총생산  |	국내총생산은 한 나라의 영역내에서 가계, 기업, 정부 등 모든 경제주체가 일정기간동안 생산활동에 참여하여 창출한 부가가치 또는 최종생산물을 시장가격으로 평가한 합계로서 여기에는 국내에 거주하는비거주자(외국인)에게 지불되는 소득과 국내 거주자가 외국에 용역을제공함으로써 수취한 소득이 포함된다.우리나라 국내총생산은 1998년 현재 450조원으로 규모면에서 세계17위권이다.	| {'國內總生産', 'GDP'}
국내총생산(GDP)  |	국내총생산(GDP; Gross Domestic Product)은 한 나라의 영역 내에서 가계, 기업, 정부등 모든 경제 주체가 일정 기간 동안 생산활동에 참여하여 창출한 부가가치 또는 최종 생산물을 시장가격으로 평가한 합계로서여기에는 국내에 거주하는 비거주자(외국인)에게 지급되는 소득도 포함된다. 한편 가격의 적용방법에 따라명목GDP(Nominal GDP)와 실질GDP(Real GDP)로 구분되며, 명목GDP는 국가경제의 규모나 구조 등을파악하는 데 사용되며 실질GDP는 경제성장, 경기변동 등 전반적인 경제활동의 흐름을 분석하는 데 이용된다.	
국내총생산(GDP)/국민총생산(GNP)  |	국내총생산 (GDP: Gross Domestic Product)은 ‘한 나라 영토 내에서 일정 기간 동안 생산된 모든 최종생산물과 서비스의 시장가치의 합’이다. 이 값은 ‘한 나라 영토 내에서 일정 기간 동안 생산된 부가가치의 합’과 동일하다. 국민총생산(GNP: Gross National Product)은 ‘한 나라 국민이 일정 기간 동안 생산한 모든 최종생산물과 서비스의 시장가치의 합’이다. GDP가 영토 중심의 개념인 반면, GNP는 생산 주체가 우리나라 국민인지 여부가 중요한 기준이다.	
국내 총생산 |	국민 총생산(GNP)에서 해외로부터의 순소득을 뺀 것이며, 어느 한 나라의 순전한 국내 경제 활동의 지표. 우리나라에서는 1995년 4/4분기부터 경제 규모를 나타내는 지표로서 국민 총생산(GNP) 대신 국내 총생산(GDP)를 사용한다.	| {'國內總生産', 'Gross Domestic Product'}
국내 총생산 |	국민 총생산에서 투자 수익 따위의 해외로부터의 순소득을 제외한 지표. 경제 성장의 대외 비교에 쓴다.	| {'지디피', '國內總生産'}
GDP      |	 국민 총생산에서 해외로부터의 순소득을 뺀 것이며  어느 한 나라의 순전한 국내경제활동의 지표로서 쓰여진다.  영국, 서독 등  GNP(국민총생산) 가운데 해외에서의 순소득이 많이  차지하는 나라에서 국내경제활동의 동향을 조사하려면 GNP보다도 GDP를 사용하는 것이 적당할 때가 있다	| {'gross domestic product', '국내총생산'}
GDP      |	 국내에서 일정기간 내에 발생된 재화와 용역의 순가치를 생산면에서 포착한 총합계액	|
지디피	   |   국민 총생산에서 투자 수익 따위의 해외로부터의 순소득을 제외한 지표. 경제 성장의 대외 비교에 쓴다.	| {'국내 총생산', 'GDP'}
'''

In [34]:
df_dedup[df_dedup['용어']=='국내총생산']

,용어,설명,details_group
7182,국내총생산,한 나라의 경제규모를 나타내는 지표. 가계·기업·정부 등 경제 주체들이 일정기간 동...,"{국내 총생산, GDP, 國內總生産, Gross Domestic Product, 지..."

In [35]:
df_dedup[df_dedup['용어']=='국내 총생산']

Empty DataFrame
Columns: [용어, 설명, details_group]
Index: []

In [36]:
df_dedup[df_dedup['용어']=='국내총생산(GDP)']

Empty DataFrame
Columns: [용어, 설명, details_group]
Index: []

In [27]:
df_dedup[df_dedup['용어']=='GDP']

Empty DataFrame
Columns: [용어, 설명, details_group]
Index: []

In [28]:
df_dedup[df_dedup['용어']=='지디피']

Empty DataFrame
Columns: [용어, 설명, details_group]
Index: []

In [29]:
df_dedup[df_dedup['용어']=='국내총생산(GDP)/국민총생산(GNP)']

Empty DataFrame
Columns: [용어, 설명, details_group]
Index: []

In [165]:
df_dedup.to_csv('통합_pre.csv', index=False)